export const BOARDS = [
  {
    id: "m5stickcplus_11",
    name: "M5StickC Plus 1.1",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "NFC", "IR", "Encoder"],
    port: "USB-C",
    baud: 115200,
    flashBaud: 115200,
    bootloader: "Auto (no buttons)",
    storage: "LittleFS only",
    bootNotes: "Auto-enters download mode. If flashing fails, hold Button A while plugging USB-C.",
    nav: [
      ["Default (Buttons)", [
        { input: "AXP power button", action: "Up" },
        { input: "BTN_A — front button", action: "Select" },
        { input: "BTN_B — side button (short press)", action: "Down" },
        { input: "BTN_B — side button (hold >600ms)", action: "Back" },
      ], "No dedicated Back button — hold BTN_B to go back."],
      ["With M5Hat Mini EncoderC", [
        { input: "Encoder CCW (left turn)", action: "Up" },
        { input: "Encoder CW (right turn)", action: "Down" },
        { input: "Encoder push", action: "Select" },
        { input: "BTN_A (short press, release)", action: "Back" },
        { input: "AXP power button", action: "Left" },
        { input: "BTN_B (press, release)", action: "Right" },
      ], null],
    ],
  },
  {
    id: "m5stickcplus_2",
    name: "M5StickC Plus 2",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "NFC", "IR", "Encoder"],
    port: "USB-C",
    baud: 115200,
    bootloader: "Auto (no buttons)",
    storage: "LittleFS only",
    bootNotes: "Same procedure as v1.1. 200mAh battery — keep plugged while flashing.",
    nav: [
      ["Default (Buttons)", [
        { input: "BTN_UP — top button", action: "Up" },
        { input: "BTN_A — front button", action: "Select" },
        { input: "BTN_B — bottom button (short press)", action: "Down" },
        { input: "BTN_B — bottom button (hold >600ms)", action: "Back" },
      ], "No dedicated Back button — hold BTN_B to go back."],
      ["With M5Hat Mini EncoderC", [
        { input: "Encoder CCW (left turn)", action: "Up" },
        { input: "Encoder CW (right turn)", action: "Down" },
        { input: "Encoder push", action: "Select" },
        { input: "BTN_A (short press, release)", action: "Back" },
        { input: "BTN_UP (press, release)", action: "Left" },
        { input: "BTN_B (press, release)", action: "Right" },
      ], null],
    ],
  },
  {
    id: "m5sticks3",
    name: "M5Stick S3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "USB HID"],
    port: "USB-C (native)",
    baud: 921600,
    bootloader: "Auto via native USB",
    storage: "LittleFS only",
    bootNotes: "Native USB — no UART chip. If bricked, hold BOOT while plugging USB to force download mode.",
    knownIssues: ["IR receive not functional — RMT conflict with ES8311 speaker; IR transmit works normally"],
    nav: [
      ["Buttons", [
        { input: "BTN_A — front button", action: "Select" },
        { input: "BTN_B — single press", action: "Down" },
        { input: "BTN_B — double press (≤250ms)", action: "Up" },
        { input: "BTN_B — hold >600ms", action: "Back" },
      ], null],
    ],
  },
  {
    id: "m5_cardputer",
    name: "M5 Cardputer",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "Keyboard", "USB HID"],
    port: "USB-C (native)",
    baud: 921600,
    bootloader: "Hold G0 + tap RESET",
    storage: "SD + LittleFS",
    bootNotes: "Full QWERTY. Enter bootloader: hold G0, tap RESET, release G0.",
    nav: [
      ["Keyboard", [
        { input: "Key ;", action: "Up" },
        { input: "Key .", action: "Down" },
        { input: "Key ,", action: "Left" },
        { input: "Key /", action: "Right" },
        { input: "Enter", action: "Select" },
        { input: "Backspace", action: "Back" },
      ], null],
    ],
  },
  {
    id: "m5_cardputer_adv",
    name: "M5 Cardputer ADV",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Keyboard", "USB HID"],
    port: "USB-C (native)",
    baud: 921600,
    bootloader: "Hold G0 + tap RESET",
    storage: "SD + LittleFS",
    bootNotes: "Same keyboard as standard Cardputer; advanced pinout adds internal GPIO header.",
    nav: [
      ["Keyboard", [
        { input: "Key ;", action: "Up" },
        { input: "Key .", action: "Down" },
        { input: "Key ,", action: "Left" },
        { input: "Key /", action: "Right" },
        { input: "Enter", action: "Select" },
        { input: "Backspace", action: "Back" },
      ], null],
    ],
  },
  {
    id: "m5_cores3",
    name: "M5 CoreS3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Touch", "USB HID"],
    port: "USB-C (native)",
    baud: 921600,
    bootloader: "Hold BTN A while connecting USB-C",
    storage: "SD + LittleFS",
    bootNotes: "Touch-first UI; physical buttons are hidden. Use on-screen controls for navigation.",
    knownIssues: [],
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 80)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
  {
    id: "t_display",
    name: "T-Display",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "USB HID"],
    port: "Micro-USB (CH9102)",
    baud: 921600,
    bootloader: "Hold BOOT + tap EN",
    storage: "LittleFS only",
    bootNotes: "Older CH9102 USB-UART — Windows may need driver. Manual bootloader entry required.",
    nav: [
      ["Buttons", [
        { input: "BTN_UP — top button", action: "Up" },
        { input: "BTN_B — bottom button (single click)", action: "Down" },
        { input: "BTN_B — bottom button (double click, ≤250ms)", action: "Select" },
        { input: "BTN_B — bottom button (hold >600ms)", action: "Back" },
      ], null],
    ],
  },
  {
    id: "t_display_s3",
    name: "T-Display S3",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "USB HID"],
    port: "USB-C (native)",
    baud: 921600,
    bootloader: "Hold BOOT + tap RST",
    storage: "LittleFS only",
    bootNotes: "Two side buttons. Hold BOOT, tap RST, release BOOT to enter download mode.",
    nav: [
      ["Buttons", [
        { input: "BTN_UP — top button", action: "Up" },
        { input: "BTN_B — bottom button (single click)", action: "Down" },
        { input: "BTN_B — bottom button (double click, ≤250ms)", action: "Select" },
        { input: "BTN_B — bottom button (hold >600ms)", action: "Back" },
      ], null],
    ],
  },
  {
    id: "t_lora_pager",
    name: "T-Lora Pager",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "NFC", "IR", "Sub-GHz", "LoRa", "Keyboard", "USB HID"],
    port: "USB-C (native)",
    baud: 921600,
    bootloader: "Hold BOOT + tap RST",
    storage: "SD + LittleFS",
    bootNotes: "Full-stack pager: SX127x LoRa + CC1101 sub-GHz. Antenna MUST be attached before TX or you will damage the radios.",
    nav: [
      ["Encoder + Keyboard", [
        { input: "Encoder — turn CCW (left)", action: "Up" },
        { input: "Encoder — turn CW (right)", action: "Down" },
        { input: "Encoder — push", action: "Select" },
        { input: "Keyboard Enter", action: "Select" },
        { input: "Keyboard Backspace", action: "Back" },
      ], null],
    ],
  },
  {
    id: "t_embed_cc1101",
    name: "T-Embed CC1101",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "Sub-GHz", "NRF24L01", "USB HID"],
    port: "USB-C (native)",
    baud: 921600,
    bootloader: "Hold BOOT + tap RST",
    storage: "SD + LittleFS",
    bootNotes: "Primary input is the rotary encoder. Push-wheel to confirm. Antenna required for Sub-GHz TX.",
    nav: [
      ["Encoder", [
        { input: "Encoder — turn CW (right)", action: "Up" },
        { input: "Encoder — turn CCW (left)", action: "Down" },
        { input: "Encoder — push", action: "Select" },
        { input: "Back button", action: "Back" },
      ], null],
    ],
  },
  {
    id: "diy_smoochie",
    name: "DIY Smoochie",
    chip: "ESP32-S3",
    tags: ["WiFi", "BLE", "IR", "NFC", "NRF24L01", "Sub-GHz", "USB HID"],
    port: "USB-C (native)",
    baud: 921600,
    bootloader: "Hold BOOT + tap RST",
    storage: "SD + LittleFS",
    bootNotes: "Community DIY build — pinout varies by batch. Check your schematic before flashing.",
    nav: [
      ["Buttons", [
        { input: "BTN_UP", action: "Up" },
        { input: "BTN_DOWN", action: "Down" },
        { input: "BTN_LEFT — short press", action: "Left" },
        { input: "BTN_LEFT — hold >600ms", action: "Back" },
        { input: "BTN_RIGHT", action: "Right" },
        { input: "BTN_SEL — center button", action: "Select" },
      ], "No dedicated Back button — hold BTN_LEFT to go back."],
    ],
  },
  {
    id: "cyd_2432s028",
    name: "CYD 2432S028",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    port: "Micro-USB (CH340)",
    baud: 921600,
    bootloader: "Auto (no buttons)",
    storage: "SD + LittleFS",
    bootNotes: "\"Cheap Yellow Display\" 2.8\" — single-USB variant, ILI9341, dedicated XPT2046 SPI. Some clones lack auto-reset; hold BOOT + tap EN if flashing fails.",
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 80)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
  {
    id: "cyd_2432w328c",
    name: "CYD 2432W328C",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    port: "Micro-USB (CH340)",
    baud: 921600,
    bootloader: "Auto (no buttons)",
    storage: "SD + LittleFS",
    bootNotes: "\"Cheap Yellow Display\" 2.8\" — capacitive touch (CST816S I2C), ILI9341 with inverted colors. Some clones lack auto-reset; hold BOOT + tap EN if flashing fails.",
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 80)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
  {
    id: "cyd_2432w328c_2",
    name: "CYD 2432W328C v2",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    port: "Micro-USB (CH340)",
    baud: 921600,
    bootloader: "Auto (no buttons)",
    storage: "SD + LittleFS",
    bootNotes: "\"Cheap Yellow Display\" 2.8\" — capacitive touch (CST816S I2C), same hardware as W328C without display color inversion. Some clones lack auto-reset; hold BOOT + tap EN if flashing fails.",
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 80)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
  {
    id: "cyd_3248s035r",
    name: "CYD 3248S035R",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    port: "Micro-USB (CH340)",
    baud: 921600,
    bootloader: "Auto (no buttons)",
    storage: "SD + LittleFS",
    bootNotes: "\"Cheap Yellow Display\" 3.5\" — ST7796 480×320 resistive touch (XPT2046 dedicated SPI). Some clones lack auto-reset; hold BOOT + tap EN if flashing fails.",
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 120)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
  {
    id: "cyd_3248s035c",
    name: "CYD 3248S035C",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    port: "Micro-USB (CH340)",
    baud: 921600,
    bootloader: "Auto (no buttons)",
    storage: "SD + LittleFS",
    bootNotes: "\"Cheap Yellow Display\" 3.5\" — ST7796 480×320 capacitive touch (GT911 I2C). Some clones lack auto-reset; hold BOOT + tap EN if flashing fails.",
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 120)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
  {
    id: "cyd_2432w328r",
    name: "CYD 2432W328R",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    port: "Micro-USB (CH340)",
    baud: 921600,
    bootloader: "Auto (no buttons)",
    storage: "SD + LittleFS",
    bootNotes: "\"Cheap Yellow Display\" — touch-only. Some clones lack auto-reset; hold BOOT + tap EN if flashing fails.",
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 80)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
  {
    id: "cyd_2432s028_2usb",
    name: "CYD 2432S028 (2USB)",
    chip: "ESP32",
    tags: ["WiFi", "BLE", "Touch"],
    port: "Micro-USB or USB-C (CH340)",
    baud: 921600,
    bootloader: "Auto (no buttons)",
    storage: "SD + LittleFS",
    bootNotes: "\"Cheap Yellow Display\" 2-USB variant — ILI9341 with inverted colors, dedicated XPT2046 SPI. Some clones lack auto-reset; hold BOOT + tap EN if flashing fails.",
    nav: [
      ["Touch", [
        { input: "Touch — left edge (x < 80)", action: "Back" },
        { input: "Touch — right top third", action: "Up" },
        { input: "Touch — right middle third", action: "Select" },
        { input: "Touch — right bottom third", action: "Down" },
      ], "Touch-only navigation. Colored edge indicators are drawn on screen to show active zones."],
    ],
  },
];

export function getBoardById(id) {
  return BOARDS.find((b) => b.id === id) || null;
}
