; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware/src
lib_dir = firmware/lib
include_dir = firmware/include
build_dir = firmware/.pio
libdeps_dir = firmware/.pio/libdeps
default_envs =
	m5stickcplus_11
	m5stickcplus_2
	t_lora_pager
	m5_cardputer
	m5_cardputer_adv
	t_display
	t_display_s3
	t_display_s3_touch
	diy_smoochie
	t_embed_cc1101
	m5_cores3
	m5sticks3
	cyd_2432w328r
	cyd_2432s028
	cyd_2432s028_2usb
	cyd_2432w328c
	cyd_2432w328c_2
	cyd_3248s035r
	cyd_3248s035c
boards_dir = firmware/boards/_devices
extra_configs = 
	firmware/boards/*.ini
	firmware/boards/*/*.ini

[env]
platform = espressif32@6.13.0
framework = arduino
board_build.variants_dir = firmware/boards
board_build.filesystem = littlefs

upload_speed = 1500000
monitor_speed = 115200

lib_deps =
	Bodmer/TFT_eSPI@^2.5.43
	Bodmer/TJpg_Decoder@^1.1.0
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
	h2zero/NimBLE-Arduino@^1.4.2
	https://github.com/kkloesener/MFRC522_I2C
	mikalhart/TinyGPSPlus@^1.1.0
	https://github.com/bmorcelli/IRremoteESP8266
	https://github.com/bmorcelli/SmartRC-CC1101-Driver-Lib/
	nrf24/RF24@^1.4.11
	adafruit/Adafruit PN532
	adafruit/Adafruit BusIO

extra_scripts =
	pre:scripts/patch.py
	post:scripts/merge.py